name: trybae_solutions
description: A comprehensive business dashboard Flutter application
publish_to: 'none'
version: 1.3.5+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.2
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  file_picker: ^8.0.3
  http_parser: ^4.0.2
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication - Supabase handles all social auth
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true 
  assets:
    - .env